#!/bin/bash
#set -x
declare verbose=1

declare -x -r P9CMD="ixpc" 
declare -x -r P9SRV="ixpsrv"
declare -x -r EBBFSPORT=1234

function usage
{
  printf "USAGE: $0 <node>\n" > /dev/stderr
  exit -1
}

function ERROR
{
    printf "ERROR: $*\n" > /dev/stderr
    usage 
}

function VERBOSE
{
  ((verbose > 0)) && printf "$*\n" > /dev/stderr
}

function genport
{
  printf $RANDOM
}

function connectToNode
{
   local node=$1
   local -i cnt=100
   local -i alive=-1

   while (( cnt > 0 )); do
      ping -c 1 $node > /dev/null 2>&1
      alive=$?
      (( alive == 0 )) && break;
      ((cnt--))
   done

   if (( alive == 0 )) 
   then
      VERBOSE "$node is alive"
   fi

   return $alive
}


function processArgs
{
  local    origargs="$@"
  local -i optcount=0
  
  while getopts "h" OPT
  do 
    case $OPT in
      ("h") usage; exit -1;;
    esac
  done
 
  shift $optcount

  node=$1

  if [[ -z $node ]]
  then
    ERROR "must specify node"
  fi
}

# main()

declare -x -r baseport=$(genport)
declare -x -r dir=${baseport}.$$.dir
declare -x -r console=${dir}/console
declare node

processArgs $@

if [[ -a $dir ]]
then
  printf "ERROR $0: $dir exists!\n" > /dev/stderr
  usage
else  
  mkdir $dir
fi

