#ifndef __EBB_CONSTS_H__
#define __EBB_CONSTS_H__

#include __LRTINC(EBBConst.h)

#define EBB_TRANS_MAX_NODES (1024)
#define EBB_TRANS_PAGE_SIZE (4096)
#define EBB_TRANS_NUM_PAGES (1024)
#define EBB_TRANS_MAX_ELS LRT_TRANS_MAX_ELS
#define EBB_TRANS_MAX_FUNCS (256)

#endif
