#!/bin/bash
# my script for setting up a friendly build tree

#set -x
DEBUGDIRS="debug ndebug partdebug"

dir=$1

if [[ -z $dir ]]
then
    dir=$(basename $(pwd))
    cd ..
fi

if [[ ! -a $dir/configure.ac ]]
then
  echo "ERROR: $dir does not seem to be a src dir"
  exit -1
fi

(cd $dir; autoreconf --install)

if [[ ! -a $dir/configure ]]
then
  echo "ERROR: $dir/configure not found"
  exit -1
fi


builddir=$dir/../build
sysdir=$builddir/$(uname -s)
system=$(uname -s)

mkdir -p $sysdir

case $system in
    Darwin)
	XFLG="--build=x86_64-darwin"
	;;
esac

for dl in $DEBUGDIRS
do
  mkdir $sysdir/$dl
  case $dl in
  debug)
    flags="-O0 -g"
    ;;
  ndebug)
    flags="-O3"
    ;;
  partdebug)
    flags="-O2 -g"
    ;;
  esac
  if [ ! -z "$EBBCC" ]; then 
      echo -n "CC=$EBBCC CXX=$EBBCXX " > $sysdir/$dl/doconfig
  else 
      echo "NO definition for EBBCC, defaulting to system compiler"
      echo -n "" > $sysdir/$dl/doconfig
  fi
  echo "../../../$dir/configure 'CFLAGS=$flags' --enable-simple-prim-alloc 'CXXFLAGS=$flags' $XFLG" >> $sysdir/$dl/doconfig
  (cd $sysdir/$dl; . doconfig)
done

cat > $sysdir/Makefile << EOF
all: .DEFAULT
.DEFAULT:
	make -C debug \${MAKECMDGOALS}
	make -C ndebug \${MAKECMDGOALS}
	make -C partdebug \${MAKECMDGOALS}
EOF

if [[ ! -a $buildir/Makefile ]]
then
cat > $builddir/Makefile << EOF
sys := \$(shell uname -s)
all: .DEFAULT
.DEFAULT:
	make -C \${sys} \${MAKECMDGOALS}
EOF
fi
echo "Build directory $sysdir ready."
echo "Issue 'make' in $builddir or $sysdir on a $(uname -s) machine to build all debug levels"
