#!/bin/sh -e

while [ ! -d .git ] && [ ! "$PWD" = "/" ] ; do
  cd ..
done

if [ ! -d .git ] ; then
  echo "Error : not in source directory" >&2
  exit 1
fi

autoreconf -i

opwd="$PWD"

mkdir ../distcheck-build
cd ../distcheck-build

"$opwd"/configure --enable-simple-prim-alloc
make distcheck
cd "$opwd"

rm -r ../distcheck-build

