#!/bin/bash
set -x

function runalltests {
  ./bindtst/bindtst $1
  rc=$?
  if [[ $rc != 0 ]] ; then 
      echo "bindtst failed" >& 2
      exit $rc
  fi	
  ./msgtst/msgtst $1
  rc=$?
  if [[ $rc != 0 ]] ; then 
     echo "msgtst failed" >& 2
     exit $rc
  fi	
}

cd apps;
if [[ "$1" == f ]] ; then
  for i in {1..61} 
  do
    runalltests "-ebbos_cores $i"
  done
else
  echo "---- running all test with 1 cores ---"
  runalltests "-ebbos_cores 1"
  echo "---- running all test with default cores ---"
  runalltests 
  echo "---- running all test with 63 cores ---"
  runalltests "-ebbos_cores 64"
fi
