#!/bin/bash
#set -x

function runalltests {
  echo "running bindtst with args " $1
  ./bindtst/bindtst $1 > last_res
  rc=$?
  if [[ $rc != 0 ]] ; then 
      echo "bindtst failed" >& 2
      exit $rc
  fi	
  echo "running msgtst with args " $1
  ./msgtst/msgtst $1 > last_res
  rc=$?
  if [[ $rc != 0 ]] ; then 
     echo "msgtst failed" >& 2
     exit $rc
  fi	
  echo "running primalloctst with args " $1
  ./primalloctst/primalloctst $1 > last_res
  rc=$?
  if [[ $rc != 0 ]] ; then 
     echo "primalloctst failed" >& 2
     exit $rc
  fi	
}

cd apps;
if [[ "$1" == f ]] ; then
  for i in {1..61} 
  do
    runalltests "-ebbos_cores $i"
  done
else
  echo "---- running all test with 1 cores ---"
  runalltests "-ebbos_cores 1"
  echo "---- running all test with default cores ---"
  runalltests 
  echo "---- running all test with 63 cores ---"
  runalltests "-ebbos_cores 63"
fi
